apiVersion: v1
kind: ConfigMap
metadata:
  name: quake3-server-config
data:
  config.yaml: |
    fragLimit: 25
    timeLimit: 15m
    bot:
      minPlayers: 3
    game:
      motd: "Welcome to Local Quake-Kube Testing"
      type: FreeForAll
      forceRespawn: false
      inactivity: 10m
      quadFactor: 3
      weaponRespawn: 3
    server:
      hostname: "quakekube-local"
      maxClients: 12
      password: "changeme"
    maps:
    - name: q3dm7
      type: FreeForAll
    - name: q3dm17
      type: FreeForAll
    - name: q3wctf1
      type: CaptureTheFlag
      captureLimit: 8
    - name: q3tourney2
      type: Tournament
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quake-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      run: quake-kube
  template:
    metadata:
      labels:
        run: quake-kube
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: server
          image: docker.io/grahamplata/quake:latest
          imagePullPolicy: Always
          command:
            - q3
            - server
            - --config=/config/config.yaml
            - --agree-eula
            - --assets-dir=/assets
            - --content-server=http://127.0.0.1:9090
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
            - containerPort: 27960
              protocol: UDP
              name: game
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          volumeMounts:
            - name: quake3-server-config
              mountPath: /config
            - name: quake3-content
              mountPath: /assets
        - name: content-server
          image: docker.io/grahamplata/quake:latest
          imagePullPolicy: Always
          command:
            - q3
            - content
            - --addr=:9090
            - --assets-dir=/assets
          ports:
            - containerPort: 9090
              protocol: TCP
              name: content
          volumeMounts:
            - name: quake3-content
              mountPath: /assets
      volumes:
        - name: quake3-server-config
          configMap:
            name: quake3-server-config
        - name: quake3-content
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: quake-kube
spec:
  type: NodePort
  selector:
    run: quake-kube
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
      protocol: TCP
      name: client
    - port: 27960
      targetPort: 27960
      nodePort: 30003
      protocol: UDP
      name: game
    - port: 9090
      targetPort: 9090
      nodePort: 30002
      protocol: TCP
      name: content
