//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BotConfigSpec) DeepCopyInto(out *BotConfigSpec) {
	*out = *in
	if in.MinPlayers != nil {
		in, out := &in.MinPlayers, &out.MinPlayers
		*out = new(int)
		**out = **in
	}
	if in.Skill != nil {
		in, out := &in.Skill, &out.Skill
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BotConfigSpec.
func (in *BotConfigSpec) DeepCopy() *BotConfigSpec {
	if in == nil {
		return nil
	}
	out := new(BotConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameConfigSpec) DeepCopyInto(out *GameConfigSpec) {
	*out = *in
	if in.Inactivity != nil {
		in, out := &in.Inactivity, &out.Inactivity
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.QuadFactor != nil {
		in, out := &in.QuadFactor, &out.QuadFactor
		*out = new(int)
		**out = **in
	}
	if in.WeaponRespawn != nil {
		in, out := &in.WeaponRespawn, &out.WeaponRespawn
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameConfigSpec.
func (in *GameConfigSpec) DeepCopy() *GameConfigSpec {
	if in == nil {
		return nil
	}
	out := new(GameConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayReference) DeepCopyInto(out *GatewayReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayReference.
func (in *GatewayReference) DeepCopy() *GatewayReference {
	if in == nil {
		return nil
	}
	out := new(GatewayReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewaySpec) DeepCopyInto(out *GatewaySpec) {
	*out = *in
	if in.GatewayRef != nil {
		in, out := &in.GatewayRef, &out.GatewayRef
		*out = new(GatewayReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewaySpec.
func (in *GatewaySpec) DeepCopy() *GatewaySpec {
	if in == nil {
		return nil
	}
	out := new(GatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MapSpec) DeepCopyInto(out *MapSpec) {
	*out = *in
	if in.CaptureLimit != nil {
		in, out := &in.CaptureLimit, &out.CaptureLimit
		*out = new(int)
		**out = **in
	}
	if in.FragLimit != nil {
		in, out := &in.FragLimit, &out.FragLimit
		*out = new(int)
		**out = **in
	}
	if in.TimeLimit != nil {
		in, out := &in.TimeLimit, &out.TimeLimit
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MapSpec.
func (in *MapSpec) DeepCopy() *MapSpec {
	if in == nil {
		return nil
	}
	out := new(MapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuakeServer) DeepCopyInto(out *QuakeServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuakeServer.
func (in *QuakeServer) DeepCopy() *QuakeServer {
	if in == nil {
		return nil
	}
	out := new(QuakeServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuakeServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuakeServerList) DeepCopyInto(out *QuakeServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QuakeServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuakeServerList.
func (in *QuakeServerList) DeepCopy() *QuakeServerList {
	if in == nil {
		return nil
	}
	out := new(QuakeServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuakeServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuakeServerSpec) DeepCopyInto(out *QuakeServerSpec) {
	*out = *in
	if in.TemplateRef != nil {
		in, out := &in.TemplateRef, &out.TemplateRef
		*out = new(TemplateReference)
		**out = **in
	}
	if in.ServerConfig != nil {
		in, out := &in.ServerConfig, &out.ServerConfig
		*out = new(ServerConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(GatewaySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.PodSecurityContext != nil {
		in, out := &in.PodSecurityContext, &out.PodSecurityContext
		*out = new(v1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(v1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuakeServerSpec.
func (in *QuakeServerSpec) DeepCopy() *QuakeServerSpec {
	if in == nil {
		return nil
	}
	out := new(QuakeServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuakeServerStatus) DeepCopyInto(out *QuakeServerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuakeServerStatus.
func (in *QuakeServerStatus) DeepCopy() *QuakeServerStatus {
	if in == nil {
		return nil
	}
	out := new(QuakeServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuakeServerTemplate) DeepCopyInto(out *QuakeServerTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuakeServerTemplate.
func (in *QuakeServerTemplate) DeepCopy() *QuakeServerTemplate {
	if in == nil {
		return nil
	}
	out := new(QuakeServerTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuakeServerTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuakeServerTemplateList) DeepCopyInto(out *QuakeServerTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QuakeServerTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuakeServerTemplateList.
func (in *QuakeServerTemplateList) DeepCopy() *QuakeServerTemplateList {
	if in == nil {
		return nil
	}
	out := new(QuakeServerTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuakeServerTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuakeServerTemplateSpec) DeepCopyInto(out *QuakeServerTemplateSpec) {
	*out = *in
	if in.ServerConfig != nil {
		in, out := &in.ServerConfig, &out.ServerConfig
		*out = new(ServerConfigSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuakeServerTemplateSpec.
func (in *QuakeServerTemplateSpec) DeepCopy() *QuakeServerTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(QuakeServerTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuakeServerTemplateStatus) DeepCopyInto(out *QuakeServerTemplateStatus) {
	*out = *in
	if in.UsedBy != nil {
		in, out := &in.UsedBy, &out.UsedBy
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuakeServerTemplateStatus.
func (in *QuakeServerTemplateStatus) DeepCopy() *QuakeServerTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(QuakeServerTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerConfigSpec) DeepCopyInto(out *ServerConfigSpec) {
	*out = *in
	if in.FragLimit != nil {
		in, out := &in.FragLimit, &out.FragLimit
		*out = new(int)
		**out = **in
	}
	if in.TimeLimit != nil {
		in, out := &in.TimeLimit, &out.TimeLimit
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Game != nil {
		in, out := &in.Game, &out.Game
		*out = new(GameConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(ServerSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.Bot != nil {
		in, out := &in.Bot, &out.Bot
		*out = new(BotConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Maps != nil {
		in, out := &in.Maps, &out.Maps
		*out = make([]MapSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Commands != nil {
		in, out := &in.Commands, &out.Commands
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerConfigSpec.
func (in *ServerConfigSpec) DeepCopy() *ServerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ServerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerSettings) DeepCopyInto(out *ServerSettings) {
	*out = *in
	if in.MaxClients != nil {
		in, out := &in.MaxClients, &out.MaxClients
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerSettings.
func (in *ServerSettings) DeepCopy() *ServerSettings {
	if in == nil {
		return nil
	}
	out := new(ServerSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateReference) DeepCopyInto(out *TemplateReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateReference.
func (in *TemplateReference) DeepCopy() *TemplateReference {
	if in == nil {
		return nil
	}
	out := new(TemplateReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationError) DeepCopyInto(out *ValidationError) {
	*out = *in
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationError.
func (in *ValidationError) DeepCopy() *ValidationError {
	if in == nil {
		return nil
	}
	out := new(ValidationError)
	in.DeepCopyInto(out)
	return out
}
