apiVersion: v1
kind: Service
metadata:
  name: {{ include "quake-kube.fullname" . }}
  labels:
    {{- include "quake-kube.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "quake-kube.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http.port }}
      targetPort: {{ .Values.service.ports.http.targetPort }}
      protocol: {{ .Values.service.ports.http.protocol | default "TCP" }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.ports.http.nodePort }}
      nodePort: {{ .Values.service.ports.http.nodePort }}
      {{- end }}
    - name: game
      port: {{ .Values.service.ports.game.port }}
      targetPort: {{ .Values.service.ports.game.targetPort }}
      protocol: {{ .Values.service.ports.game.protocol | default "UDP" }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.ports.game.nodePort }}
      nodePort: {{ .Values.service.ports.game.nodePort }}
      {{- end }}
    {{- if or (hasPrefix "127.0.0.1" (urlParse .Values.quake.contentServer).host) (hasPrefix "localhost" (urlParse .Values.quake.contentServer).host) }}
    - name: content
      port: {{ .Values.service.ports.content.port }}
      targetPort: {{ .Values.service.ports.content.targetPort }}
      protocol: {{ .Values.service.ports.content.protocol | default "TCP" }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.ports.content.nodePort }}
      nodePort: {{ .Values.service.ports.content.nodePort }}
      {{- end }}
    {{- end }}
